#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Loads the generic functions usually used in the script

# Source app helpers
source /usr/share/yunohost/helpers

# Get application informations.
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

SECURE_REMOVE '/var/www/$app'	# Delete directory application

REMOVE_NGINX_CONF	# Delete nginx configuration

REMOVE_FPM_CONF	# Delete pool php-fpm configuration

# Reload SSOwat configuration
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
